---
- hosts: all
  pre_tasks:
    - name: install required roles from ansible galaxy
      local_action: command ansible-galaxy install -r required-roles.yaml
      become: true

  tasks:
    - name: ubuntu settings
      include: ubuntu-settings.yaml

    - name: get status of copied in SSH key file
      stat: path=/tmp/id_rsa
      register: ssh_key_status

    - name: move SSH key file into place
      local_action: command mv /tmp/id_rsa /home/vagrant/.ssh/id_rsa
      when: ssh_key_status.stat.exists
      become: true

    - name: install chrome
      static: no
      include_role:
        name: cmprescott.chrome
      become: true
      
    - name: install node
      static: no
      include_role:
        name: geerlingguy.nodejs
      become: true

    - name: install terminator
      static: no
      include_role:
        name: vcabourdin.terminator
      become: true

    - name: install visual studio
      static: no
      include_role: 
        name: gantsign.visual-studio-code
      vars:
        users:
        - username: vagrant
          visual_studio_code_settings: {
            "editor.rulers": [80],
            "editor.tabsize": 2
          }
      
    - name: fix for https://github.com/Microsoft/vscode/issues/13799
      lineinfile:
        dest: /usr/share/applications/code.desktop
        regexp: Exec=/usr/share/code/code --unity-launch %U
        line: Exec=/usr/share/code/code --disable-gpu --unity-launch %U
      become: true

    - name: register github.com as a known host
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
      become: true
