---
- become: true
  hosts: all
  roles:
    - cmprescott.chrome
    - geerlingguy.nodejs
    - kbrebanov.dkms
    - ssilab.aws-cli
  tasks:
    - name: ubuntu settings
      include_tasks: ubuntu-settings.yaml

    - name: get status of copied in SSH key file
      register: ssh_key_status
      stat: path=/tmp/id_rsa

    - copy:
        src: /tmp/id_rsa
        dest: /home/vagrant/.ssh/id_rsa
        owner: vagrant
        mode: 0400
      name: move SSH key file into place
      when: ssh_key_status.stat.exists

    - name: get status of copied AWS settings
      register: aws_settings_status
      stat: path=/tmp/.aws

    - file: path=/home/vagrant/.aws state=directory
      name: Ensures AWS config directory exists
      when: aws_settings_status.stat.exists

    - copy:
        src: /tmp/.aws/credentials
        dest: /home/vagrant/.aws/credentials
        owner: vagrant
        mode: 0400
      name: move AWS CLI credentials into place
      when: aws_settings_status.stat.exists

    - copy:
        src: /tmp/.aws/config
        dest: /home/vagrant/.aws/config
        owner: vagrant
        mode: 0400
      name: move AWS CLI config into place
      when: aws_settings_status.stat.exists

    - name: install visual studio
      import_role: 
        name: gantsign.visual-studio-code
      vars:
        users:
        - username: vagrant
          visual_studio_code_extensions:
            - "dbaeumer.vscode-eslint"
            - "chrmarti.regex"
            - "streetsidesoftware.code-spell-checker"
          visual_studio_code_settings: {
            "cSpell.userWords": [
              "amazonaws",
              "babili",
              "bitbucket",
              "bottlejs",
              "borked",
              "cloudformation",
              "ciphertext",
              "craigap",
              "deployer",
              "eslintcache",
              "fullscreen",
              "gitignore",
              "gulpfile",
              "jmespath",
              "oris",
              "minimap",
              "myresearch",
              "participations",
              "prepper",
              "SCIO",
              "SDK's",
              "serverless"
            ],

            "editor.autoClosingBrackets": false,
            "editor.fontSize": 12,
            "editor.insertSpaces": true,
            "editor.minimap.enabled": false,
            "editor.rulers": [80, 100],
            "editor.tabSize": 2,

            "extensions.autoUpdate": true,

            "files.eol": "\n",
            "files.insertFinalNewline": true,
            "files.trimTrailingWhitespace": true,

            "terminal.integrated.fontSize": 12,

            "window.newWindowDimensions": "maximized"
          }
      
    - name: fix for https://github.com/Microsoft/vscode/issues/13799
      lineinfile:
        dest: /usr/share/applications/code.desktop
        line: Exec=/usr/share/code/code --disable-gpu --unity-launch %U
        regexp: Exec=/usr/share/code/code --unity-launch %U

    - name: register github.com as a known host
      known_hosts:
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        path: /etc/ssh/ssh_known_hosts
        name: github.com

    - name: get status of copied Git settings
      register: git_key_status
      stat: path=/tmp/.gitconfig
    
    - copy:
        src: /tmp/.gitconfig
        dest: /home/vagrant/.gitconfig
        owner: vagrant
        mode: 0700
      name: move Git config into place
      when: git_key_status.stat.exists
