---
- hosts: all
  pre_tasks:
    - name: install required roles from ansible galaxy
      local_action: command ansible-galaxy install -r required-roles.yaml
      become: true

  tasks:
    - name: ubuntu settings
      include: ubuntu-settings.yaml

    - name: get status of copied in SSH key file
      register: ssh_key_status
      stat: path=/tmp/id_rsa

    - copy:
        src: /tmp/id_rsa
        dest: /home/vagrant/.ssh/id_rsa
        owner: vagrant
        mode: 0400
      name: move SSH key file into place
      when: ssh_key_status.stat.exists

    - copy:
        src: /vagrant/files/ssh.config
        dest: /home/vagrant/.ssh/config
        owner: vagrant
        mode: 0700
      name: adds custom Bash profile

    - name: get status of copied AWS settings
      register: aws_settings_status
      stat: path=/tmp/.aws

    - name: install AWS CLI
      become: true
      include_role:
        name: ssilab.aws-cli
      static: no
      vars:
        - aws_output_format: json
        - aws_region: us-west-2
        - aws_access_key_id: FAKE_PLACEHOLDER
        - aws_secrete_access_key: FAKE_PLACEHOLDER
      when: aws_settings_status.stat.exists

    - copy:
        src: /tmp/.aws/credentials
        dest: /home/vagrant/.aws/credentials
        owner: vagrant
        mode: 0400
      name: move AWS CLI credentials into place
      when: aws_settings_status.stat.exists

    - copy:
        src: /tmp/.aws/config
        dest: /home/vagrant/.aws/config
        owner: vagrant
        mode: 0400
      name: move AWS CLI config into place
      when: aws_settings_status.stat.exists

    - name: install chrome
      become: true
      include_role:
        name: cmprescott.chrome
      static: no
      
    - name: install node
      become: true
      include_role:
        name: geerlingguy.nodejs
      static: no

    - name: install terminator
      become: true
      include_role:
        name: vcabourdin.terminator
      static: no

    - name: install visual studio
      become: true
      include_role: 
        name: gantsign.visual-studio-code
      static: no
      vars:
        users:
        - username: vagrant
          visual_studio_code_settings: {
            "editor.rulers": [80],
            "editor.tabsize": 2
          }
      
    - name: fix for https://github.com/Microsoft/vscode/issues/13799
      become: true
      lineinfile:
        dest: /usr/share/applications/code.desktop
        line: Exec=/usr/share/code/code --disable-gpu --unity-launch %U
        regexp: Exec=/usr/share/code/code --unity-launch %U

    - name: register github.com as a known host
      become: true
      known_hosts:
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        path: /etc/ssh/ssh_known_hosts
        name: github.com
