---
- hosts: all
  pre_tasks:
    - name: install required roles from ansible galaxy
      become: true
      local_action: command ansible-galaxy install -r required-roles.yaml

  tasks:
    - name: ubuntu settings
      include: ubuntu-settings.yaml

    - name: get status of copied in SSH key file
      register: ssh_key_status
      stat: path=/tmp/id_rsa

    - copy:
        src: /tmp/id_rsa
        dest: /home/vagrant/.ssh/id_rsa
        owner: vagrant
        mode: 0400
      name: move SSH key file into place
      when: ssh_key_status.stat.exists

    - name: get status of copied AWS settings
      register: aws_settings_status
      stat: path=/tmp/.aws

    - file: path=/home/vagrant/.aws state=directory
      name: Ensures AWS config directory exists
      when: aws_settings_status.stat.exists

    - copy:
        src: /tmp/.aws/credentials
        dest: /home/vagrant/.aws/credentials
        owner: vagrant
        mode: 0400
      name: move AWS CLI credentials into place
      when: aws_settings_status.stat.exists

    - name: install AWS CLI
      become: true
      include_role:
        name: ypsman.aws-cli
      static: no
      when: aws_settings_status.stat.exists

    - copy:
        src: /tmp/.aws/config
        dest: /home/vagrant/.aws/config
        owner: vagrant
        mode: 0400
      name: move AWS CLI config into place
      when: aws_settings_status.stat.exists

    - name: install chrome
      become: true
      include_role:
        name: cmprescott.chrome
      static: no

    - name: install dkms (guest-side part of time synching)
      become: true
      include_role:
        name: kbrebanov.dkms
      static: no
      
    - name: install node
      become: true
      include_role:
        name: geerlingguy.nodejs
      static: no

    - name: install terminator
      become: true
      include_role:
        name: vcabourdin.terminator
      static: no

    - name: install visual studio
      become: true
      include_role: 
        name: gantsign.visual-studio-code
      static: no
      vars:
        users:
        - username: vagrant
          visual_studio_code_extensions:
            - "dbaeumer.vscode-eslint"
            - "chrmarti.regex"
            - "streetsidesoftware.code-spell-checker"
          visual_studio_code_settings: {
            "cSpell.userWords": [
              "amazonaws",
              "babili",
              "bitbucket",
              "borked",
              "cloudformation",
              "ciphertext",
              "deployer",
              "eslintcache",
              "fullscreen",
              "gitignore",
              "jmespath",
              "oris",
              "minimap",
              "myresearch",
              "participations",
              "prepper",
              "SCIO",
              "SDK's",
              "serverless"
            ],

            "editor.autoClosingBrackets": false,
            "editor.fontSize": 12,
            "editor.insertSpaces": true,
            "editor.minimap.enabled": false,
            "editor.rulers": [80, 100],
            "editor.tabSize": 2,

            "extensions.autoUpdate": true,

            "files.eol": "\n",
            "files.insertFinalNewline": true,
            "files.trimTrailingWhitespace": true,

            "terminal.integrated.fontSize": 12,

            "window.newWindowDimensions": "maximized"
          }
      
    - name: fix for https://github.com/Microsoft/vscode/issues/13799
      become: true
      lineinfile:
        dest: /usr/share/applications/code.desktop
        line: Exec=/usr/share/code/code --disable-gpu --unity-launch %U
        regexp: Exec=/usr/share/code/code --unity-launch %U

    - name: register github.com as a known host
      become: true
      known_hosts:
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        path: /etc/ssh/ssh_known_hosts
        name: github.com

    - name: get status of copied Git settings
      register: git_key_status
      stat: path=/tmp/.gitconfig
    
    - copy:
        src: /tmp/.gitconfig
        dest: /home/vagrant/.gitconfig
        owner: vagrant
        mode: 0700
      name: move Git config into place
      when: git_key_status.stat.exists
